name: windows

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install OpenCL with vcpkg
      run: .\vcpkg\vcpkg.exe install opencl

    - name: Build
      run: $env:LIB += ';' + (Resolve-Path .\vcpkg\installed\x64-windows\lib); cargo build --release

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: dev-windows
        artifacts: "target/release/bacon.exe"
        prerelease: true